name = "royal-queen-2868"
main = "worker.js"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

[vars]
# 在 Cloudflare Dashboard 中设置
# HF_TOKEN = "你的 Hugging Face API Token"
# SF_TOKEN = "你的硅基流动 API Token" 