name = "video-to-text"
compatibility_date = "2024-01-17"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[[routes]]
pattern = "/api/*"
script = "functions/api/transcribe.ts" 