name = "video-to-text"
main = "src/workers/transcribe.ts"
compatibility_date = "2024-01-17"

[build]
command = "npm run build"

[[routes]]
pattern = "/api/transcribe"
script = "src/workers/transcribe.ts" 